<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:discourse="http://www.discourse.org/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Operations - StackStorm Support (ARCHIVED)</title>
    <link>https://forum.stackstorm.com/c/operations-related-issues/20</link>
    <description>Topics in the &#39;Operations&#39; category </description>
    
      <lastBuildDate>Thu, 22 Apr 2021 04:24:54 +0000</lastBuildDate>
      <atom:link href="https://forum.stackstorm.com/c/operations-related-issues/20.rss" rel="self" type="application/rss+xml" />
        <item>
          <title>Dynamic Pack credentials/configuration possible?</title>
          <dc:creator><![CDATA[willowhawk]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>At the risk of ressurecting an <a href="https://forum.stackstorm.com/t/pack-configs-different-hosts-credentials/398">old thread</a>, I have a situation where I will need to perform actions using a pack but need to change the configuration of the pack at run-time.</p>
<p>Example:<br>
I have a workflow that orchestrates actions across several different platforms, one of which is AWS.  The aws 2.0.0 pack has me configure the AWS Access Key and Secret Key in the pack configuration, which is then used by the actions.  I’ll need to target different customer was accounts, as they provide the account ID and access/secret tokens as part of the API call, and would like to reconfigure the pack for the scope of the action runner, or failing that, configure the AWS pack itself and lock operations to just that workflow until its completed to ensure no concurrent runners try to do actions in the wrong enclave.</p>
<p>I haven’t seen any native action in st2 to manipulate pack configuration, so I’m embarking on the arcane wizardry of delving into where that configuration is read from at runtime to see how to go about writing core actions to manipulate it.</p>
<p>Can someone tell me I’m crazy and point to a better way?</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/dynamic-pack-credentials-configuration-possible/1659">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/dynamic-pack-credentials-configuration-possible/1659</link>
          <pubDate>Thu, 22 Apr 2021 04:24:54 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1659</guid>
          <source url="https://forum.stackstorm.com/t/dynamic-pack-credentials-configuration-possible/1659.rss">Dynamic Pack credentials/configuration possible?</source>
        </item>
        <item>
          <title>How to pass user input as host value in action from stackstorm</title>
          <dc:creator><![CDATA[haridvpsk]]></dc:creator>
          <category>Packages</category>
          <description><![CDATA[
            <pre><code class="lang-auto">$ cat actions/docker_status.yaml 
---
name: status
pack: docker_status
runner_type: "remote-shell-script"
description: "Checking docker continer status on FPM VM's"
enabled: true
entry_point: "docker_status.sh"
parameters:
 hosts:
   immutable: true
   default: "65.0.194.82"
 private_key:
   immutable: true
   default: "/home/stanley/.ssh/test"
 username:
   immutable: true
   default: "centos"
 timeout:
   type: 'integer'
   default: 60
</code></pre>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/how-to-pass-user-input-as-host-value-in-action-from-stackstorm/1613">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/how-to-pass-user-input-as-host-value-in-action-from-stackstorm/1613</link>
          <pubDate>Wed, 24 Mar 2021 14:46:06 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1613</guid>
          <source url="https://forum.stackstorm.com/t/how-to-pass-user-input-as-host-value-in-action-from-stackstorm/1613.rss">How to pass user input as host value in action from stackstorm</source>
        </item>
        <item>
          <title>ERROR: Resource with id or reference doesn&#39;t exist</title>
          <dc:creator><![CDATA[arul]]></dc:creator>
          <category>Packages</category>
          <description><![CDATA[
            <p>Hi Team,</p>
<p>I am new to Stackstorm. I have created a simple pack &amp; actions.</p>
<p>while running the actions, I got the below error.</p>
<p>sudo st2 action execute ArulPing_st2.ping ip=40.117.95.248<br>
ERROR: Resource with id or reference “ArulPing_st2.ping” doesn’t exist.</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/error-resource-with-id-or-reference-doesnt-exist/1573">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/error-resource-with-id-or-reference-doesnt-exist/1573</link>
          <pubDate>Wed, 24 Feb 2021 12:30:00 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1573</guid>
          <source url="https://forum.stackstorm.com/t/error-resource-with-id-or-reference-doesnt-exist/1573.rss">ERROR: Resource with id or reference doesn&#39;t exist</source>
        </item>
        <item>
          <title>How to configure file based logging in stackstorm docker setup</title>
          <dc:creator><![CDATA[shanwave007]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>Hi, i need to setup all the stdout logs into a log file in my host machine. i’ve proceeded with the official documentation which is <a href="https://docs.stackstorm.com/install/config/config.html#config-logging" class="inline-onebox" rel="noopener nofollow ugc">Nginx and WSGI — StackStorm 3.3.0 documentation</a> and added</p>
<p>[handler_fileHandler]<br>
class=st2common.log.FormatNamedFileHandler<br>
level=INFO<br>
formatter=verboseConsoleFormatter<br>
args=(’/var/log/st2/st2actionrunner.{pid}.log’,)</p>
<p>But this also not working</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/how-to-configure-file-based-logging-in-stackstorm-docker-setup/1545">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/how-to-configure-file-based-logging-in-stackstorm-docker-setup/1545</link>
          <pubDate>Wed, 27 Jan 2021 05:06:37 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1545</guid>
          <source url="https://forum.stackstorm.com/t/how-to-configure-file-based-logging-in-stackstorm-docker-setup/1545.rss">How to configure file based logging in stackstorm docker setup</source>
        </item>
        <item>
          <title>Locally created st2 packs falling on stackstorm HA in kubernetes</title>
          <dc:creator><![CDATA[nithinsubbaraj]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>Locally created st2 packs falling on stackstorm HA in kubernetes.</p>
<p>The pack is working fine on standalone server but facing issue on docker image created in stackstorm HA in kubernetes.<br>
created st2 pack with docker build ,pushed and pulled the image through helm but facing issue<br>
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] ECONNREFUSED</p>
<p>2020-12-04 14:01:32,140 DEBUG [-] Using Python: 3.6.9 (/opt/stackstorm/st2/bin/python)<br>
2020-12-04 14:01:32,141 DEBUG [-] Using config files: /etc/st2/st2.conf<br>
2020-12-04 14:01:32,142 DEBUG [-] Using logging config: /etc/st2/logging.sensorcontainer.conf<br>
2020-12-04 14:01:32,151 INFO [-] Connecting to database “st2” @ “127.0.0.1:27017” as user “None”.<br>
2020-12-04 14:01:35,158 ERROR [-] Failed to connect to database “st2” @ “127.0.0.1:27017” as user “None”: 127.0.0.1:27017: [Errno 111] ECONNREFUSED<br>
2020-12-04 14:01:35,158 ERROR [-] (PID:191) SensorContainer quit due to exception.<br>
Traceback (most recent call last):<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/cmd/sensormanager.py”, line 61, in main<br>
_setup()<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/cmd/sensormanager.py”, line 52, in _setup<br>
register_runners=False, service_registry=True, capabilities=capabilities)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/service_setup.py”, line 162, in setup<br>
db_setup()<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/database_setup.py”, line 57, in db_setup<br>
connection = db_init.db_setup_with_retry(**db_cfg)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/persistence/db_init.py”, line 76, in db_setup_with_retry<br>
ssl_match_hostname=ssl_match_hostname)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/persistence/db_init.py”, line 59, in db_func_with_retry<br>
return retrying_obj.call(db_func, *args, **kwargs)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/retrying.py”, line 206, in call<br>
return attempt.get(self._wrap_exception)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/retrying.py”, line 247, in get<br>
six.reraise(self.value[0], self.value[1], self.value[2])<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/six.py”, line 696, in reraise<br>
raise value<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/retrying.py”, line 200, in call<br>
attempt = Attempt(fn(*args, **kwargs), attempt_number, False)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/models/db/<strong>init</strong>.py”, line 170, in db_setup<br>
ssl_match_hostname=ssl_match_hostname)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/models/db/<strong>init</strong>.py”, line 152, in _db_connect<br>
raise e<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/models/db/<strong>init</strong>.py”, line 145, in _db_connect<br>
connection.admin.command(‘ismaster’)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/database.py”, line 730, in command<br>
read_preference, session) as (sock_info, slave_ok):<br>
File “/usr/lib/python3.6/contextlib.py”, line 81, in <strong>enter</strong><br>
return next(self.gen)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/mongo_client.py”, line 1298, in _socket_for_reads<br>
server = self._select_server(read_preference, session)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/mongo_client.py”, line 1253, in _select_server<br>
server = topology.select_server(server_selector)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/topology.py”, line 235, in select_server<br>
address))<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/topology.py”, line 193, in select_servers<br>
selector, server_timeout, address)<br>
File “/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/topology.py”, line 209, in _select_servers_loop<br>
self._error_message(selector))<br>
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] ECONNREFUSED</p>
            <p><small>9 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/locally-created-st2-packs-falling-on-stackstorm-ha-in-kubernetes/1494">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/locally-created-st2-packs-falling-on-stackstorm-ha-in-kubernetes/1494</link>
          <pubDate>Fri, 04 Dec 2020 17:24:12 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1494</guid>
          <source url="https://forum.stackstorm.com/t/locally-created-st2-packs-falling-on-stackstorm-ha-in-kubernetes/1494.rss">Locally created st2 packs falling on stackstorm HA in kubernetes</source>
        </item>
        <item>
          <title>Stackstorm dashboard is not working</title>
          <dc:creator><![CDATA[kiran.lohar]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>I used st2-docker and its working but when i try to visit web UI(dashboard) i got error which is " This site can’t be reached". i used version 3.1.0<br>
please give me any suggestion what to do next.</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/stackstorm-dashboard-is-not-working/1486">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/stackstorm-dashboard-is-not-working/1486</link>
          <pubDate>Tue, 01 Dec 2020 13:09:47 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1486</guid>
          <source url="https://forum.stackstorm.com/t/stackstorm-dashboard-is-not-working/1486.rss">Stackstorm dashboard is not working</source>
        </item>
        <item>
          <title>Questions regarding st2 pack on stackstorm HA in kubernetes</title>
          <dc:creator><![CDATA[nithinsubbaraj]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>Hi Team,</p>
<p>I have few queries regarding stackstorm packs for stackstorm ha on kubernetes.</p>
<p>1)I figured out to how to create a docker image for service now and create a docker image and use it helm configuration</p>
<p>2)I am trying to copy the st2 packs from standalone server to the stackstorm ha in kubernetes.<br>
The names are like test_ansible,hello_st2 etc</p>
<p>when I try to create a docker image gettign the error:</p>
<p>docker build -t st2packs_test:0.9 --build-arg PACKS=hello_st2 st2packs-image</p>
<p>2020-11-24 14:27:06,523 INFO [-] Installing pack “hello_st2”<br>
2020-11-24 14:27:06,839 ERROR [-] Failed to install pack “hello_st2”: No record of the “hello_st2” pack in the index.<br>
The command ‘/bin/sh -c /opt/stackstorm/st2/bin/st2-pack-install ${PACKS}’ returned a non-zero code: 2</p>
<p>Is there a way I can add the name to the index ,if so how to do</p>
<p>[root@dc1udataocs301 st2packs-dockerfiles]# docker build -t st2packs_test:0.9 --build-arg PACKS=hello_st2 st2packs-image<br>
Sending build context to Docker daemon  5.662MB<br>
Step 1/7 : ARG PACKS=“file:///tmp/stackstorm-st2”<br>
Step 2/7 : FROM stackstorm/st2packs:builder AS builder</p>
<h1>Executing 2 build triggers</h1>
<p>—&gt; Using cache<br>
—&gt; Running in da4ddcebc38b<br>
Removing intermediate container da4ddcebc38b<br>
—&gt; 3b1cdbeeb9ab<br>
Step 3/7 : COPY packs/hello_st2  /tmp/stackstorm-st2/<br>
—&gt; 20edfa1b5f12<br>
Step 4/7 : RUN ls -la /tmp/stackstorm-st2<br>
—&gt; Running in 04766987ebc3<br>
total 12<br>
drwxr-xr-x 7 root root  137 Nov 24 14:26 .<br>
drwxrwxrwt 1 root root   28 Nov 24 14:26 …<br>
drwxr-xr-x 2 root root   40 Aug 12 18:04 actions<br>
drwxr-xr-x 2 root root   25 Aug 12 18:04 aliases<br>
-rw-r–r-- 1 root root 3936 Aug 12 17:58 icon.png<br>
-rw-r–r-- 1 root root 1285 Aug 12 17:58 pack.yaml<br>
drwxr-xr-x 2 root root   65 Aug 12 18:04 policies<br>
-rw-r–r-- 1 root root    9 Aug 12 17:58 requirements.txt<br>
drwxr-xr-x 2 root root   24 Aug 12 18:04 rules<br>
drwxr-xr-x 2 root root   44 Aug 12 18:04 sensors<br>
Removing intermediate container 04766987ebc3<br>
—&gt; b685fd70a9da<br>
Step 5/7 : RUN git config --global http.sslVerify false<br>
—&gt; Running in 8d38579121e3<br>
Removing intermediate container 8d38579121e3<br>
—&gt; 4d6386076124<br>
Step 6/7 : RUN /opt/stackstorm/st2/bin/st2-pack-install <span class="math">{PACKS}
 ---&gt; Running in 24a099672558
2020-11-24 14:27:06,523 INFO [-] Installing pack "hello_st2"
2020-11-24 14:27:06,839 ERROR [-] Failed to install pack "hello_st2": No record of the "hello_st2" pack in the index.
The command '/bin/sh -c /opt/stackstorm/st2/bin/st2-pack-install </span>{PACKS}’ returned a non-zero code: 2</p>
<p>3)I tried to create multiple st2packs eg:</p>
<p>docker build --build-arg PACKS=servicenow ansible jira -t st2:0.1 st2packs-image</p>
<p>but no luck then I tried</p>
<p>docker build -t st2packs_test:0.2 --build-arg PACKS=servicenow  --build-arg PACKS=ansible  --build-arg PACKS=jira st2packs-image</p>
<p>the command executes only the last one eg servicenow ,ansible and jira ,it takes only jira.</p>
<p>Also facing the issue for ansible pack when installed alone ,for standalone also was facing the issue ,then install gcc with<br>
yum install gcc and it worked ,not sure how do it for docker</p>
<p>Step 1/7 : ARG PACKS=“file:///tmp/stackstorm-st2”<br>
Step 2/7 : FROM stackstorm/st2packs:builder AS builder</p>
<h1>Executing 2 build triggers</h1>
<p>—&gt; Using cache<br>
—&gt; Using cache<br>
—&gt; 16cc22f2cba9<br>
Step 3/7 : COPY packs/hello_st2  /tmp/stackstorm-st2/<br>
—&gt; Using cache<br>
—&gt; 4b2b0294c1c7<br>
Step 4/7 : RUN ls -la /tmp/stackstorm-st2<br>
—&gt; Using cache<br>
—&gt; d6125dc06c83<br>
Step 5/7 : RUN git config --global http.sslVerify false<br>
—&gt; Using cache<br>
—&gt; 5b68c4ea031a<br>
Step 6/7 : RUN /opt/stackstorm/st2/bin/st2-pack-install ${PACKS}<br>
—&gt; Running in 9e02c88c3d1d<br>
2020-11-24 15:17:51,629 INFO [-] Installing pack “ansible”<br>
2020-11-24 15:17:52,430 INFO [-] Successfully installed pack “ansible”<br>
2020-11-24 15:17:52,431 INFO [-] Setting up virtualenv for pack “ansible”<br>
2020-11-24 15:17:52,432 INFO [-] Virtualenv path “/opt/stackstorm/virtualenvs/ansible” doesn’t exist</p>
<p>error:<br>
----------------------------------------<br>
ERROR: Command “/opt/stackstorm/virtualenvs/ansible/bin/python -u -c ‘import setuptools, tokenize;<strong>file</strong>=’”’"’/tmp/pip-install-stuuz20m/pykerberos/setup.py’"’"’;f=getattr(tokenize, ‘"’"‘open’"’"’, open)(<strong>file</strong>);code=f.read().replace(’"’"’\r\n’"’"’, ‘"’"’\n’"’"’);f.close();exec(compile(code, <strong>file</strong>, ‘"’"‘exec’"’"’))’ install --record /tmp/pip-record-em0jpki_/install-record.txt --single-version-externally-managed --compile --install-headers /opt/stackstorm/virtualenvs/ansible/include/site/python3.6/pykerberos" failed with error code 1 in /tmp/pip-install-stuuz20m/pykerberos/<br>
WARNING: You are using pip version 19.1.1, however version 20.2.4 is available.<br>
You should consider upgrading via the ‘pip install --upgrade pip’ command.<br>
)</p>
<p>pip install --upgrade pip<br>
Requirement already up-to-date: pip in /usr/local/lib/python3.6/site-packages (20.2.4)</p>
<p>docker build -t st2packs_test:0.2 --build-arg PACKS=servicenow  --build-arg PACKS=jira  --build-arg PACKS=ansible st2packs-image</p>
<p>docker build -t st2packs_test:0.2 --build-arg PACKS=ansible st2packs-image</p>
            <p><small>9 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/questions-regarding-st2-pack-on-stackstorm-ha-in-kubernetes/1484">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/questions-regarding-st2-pack-on-stackstorm-ha-in-kubernetes/1484</link>
          <pubDate>Tue, 24 Nov 2020 15:26:58 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1484</guid>
          <source url="https://forum.stackstorm.com/t/questions-regarding-st2-pack-on-stackstorm-ha-in-kubernetes/1484.rss">Questions regarding st2 pack on stackstorm HA in kubernetes</source>
        </item>
        <item>
          <title>Custom st2 packs on stackstorm HA in kubernetes</title>
          <dc:creator><![CDATA[nithinsubbaraj]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>Hi All,</p>
<p>I have installed  a basic stackstorm HA in kubernetes with helm.<br>
helm repo add stackstorm <a href="https://helm.stackstorm.com/" rel="noopener nofollow ugc">https://helm.stackstorm.com/</a><br>
helm install stackstorm/stackstorm-ha</p>
<p>I was trying to add the packs like servicenow and ansible.</p>
<p>Inside the stackstorm docker instance got the error</p>
<p>On checking the docs found <a href="https://github.com/StackStorm/st2packs-dockerfiles/" class="inline-onebox" rel="noopener nofollow ugc">GitHub - StackStorm/st2packs-dockerfiles: Source for st2packs-builder and st2packs-runner images</a><br>
git clone <a href="https://github.com/StackStorm/st2packs-dockerfiles" class="inline-onebox" rel="noopener nofollow ugc">GitHub - StackStorm/st2packs-dockerfiles: Source for st2packs-builder and st2packs-runner images</a><br>
cd st2packs-dockerfiles<br>
docker build --build-arg PACKS=servicenow  -t st2packs:1 st2packs-image</p>
<p>Sending build context to Docker daemon  4.608kB<br>
Step 1/3 : FROM stackstorm/st2packs:builder AS builder</p>
<h1>Executing 2 build triggers</h1>
<p>—&gt; Using cache<br>
—&gt; Using cache<br>
—&gt; c4b8aecca64e<br>
Step 2/3 : RUN /opt/stackstorm/st2/bin/st2-pack-install ${PACKS}<br>
—&gt; Using cache<br>
—&gt; 2063f3e71c99<br>
Step 3/3 : FROM stackstorm/st2packs:runtime</p>
<h1>Executing 3 build triggers</h1>
<p>—&gt; Using cache<br>
—&gt; Using cache<br>
—&gt; Using cache<br>
—&gt; 393a047e7d41<br>
Successfully built 393a047e7d41<br>
Successfully tagged st2packs:1</p>
<p>docker ps -a |grep -i st2packs<br>
a808db5d5f9e        st2packs:1    “/bin/sh” 12 seconds ago Exited (0) 11 seconds ago  st2packs</p>
<p>st2packs    393a047e7d41        23 hours ago        125MB</p>
<p>Created  a sample servicenow image pack .</p>
<p>The question is<br>
1)Is this the correct way to create a additional pack ,how does this created pack<br>
work with stackstorm HA<br>
2)IS there a way were we can download or install pack on base OS and redirect the data to the docker stackstom HA<br>
3)I am not sure how to make the st2 pack image work with stackstom HA docker<br>
4)Also when we install stackstorm ha with helm repo does it store the values.yaml in any particular path<br>
I downlaod the values.yaml from git and forced it to use the new value with<br>
helm install -f custom_values.yaml</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/custom-st2-packs-on-stackstorm-ha-in-kubernetes/1457">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/custom-st2-packs-on-stackstorm-ha-in-kubernetes/1457</link>
          <pubDate>Tue, 20 Oct 2020 13:26:51 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1457</guid>
          <source url="https://forum.stackstorm.com/t/custom-st2-packs-on-stackstorm-ha-in-kubernetes/1457.rss">Custom st2 packs on stackstorm HA in kubernetes</source>
        </item>
        <item>
          <title>Action class logs cannot be found in any log file</title>
          <dc:creator><![CDATA[Tarto]]></dc:creator>
          <category>Packages</category>
          <description><![CDATA[
            <p>Hi everyone, I have recently changed the log formatter and handler to GELF. I don’t see logs for the action python class that I have logged, checked in st2actionrunner.gelf.log or st2actionrunner.audit.log or st2actionrunner.log but I do see the logs for sensor in under st2sensorcontainer.gelf.log . I’m not sure how to debug this, or why are the logs not to be found anywhere for actions. Could someone please help if they have seen this issue before? Thank you.</p>
            <p><small>13 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/action-class-logs-cannot-be-found-in-any-log-file/1427">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/action-class-logs-cannot-be-found-in-any-log-file/1427</link>
          <pubDate>Wed, 23 Sep 2020 04:05:45 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1427</guid>
          <source url="https://forum.stackstorm.com/t/action-class-logs-cannot-be-found-in-any-log-file/1427.rss">Action class logs cannot be found in any log file</source>
        </item>
        <item>
          <title>Graceful stop of action runners</title>
          <dc:creator><![CDATA[denis-rodionov]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>Do you know, is it possible to perform a graceful stop of an action runner to avoid interruption of the running actions and waiting until they are completed before stopping the process?</p>
            <p><small>4 posts - 3 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/graceful-stop-of-action-runners/1407">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/graceful-stop-of-action-runners/1407</link>
          <pubDate>Fri, 28 Aug 2020 10:26:35 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1407</guid>
          <source url="https://forum.stackstorm.com/t/graceful-stop-of-action-runners/1407.rss">Graceful stop of action runners</source>
        </item>
        <item>
          <title>Canceling action execution</title>
          <dc:creator><![CDATA[denis-rodionov]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>We noticed, that even if you click “Cancel” in WebUI during the action execution, the action still continued running:<br>
StackStorm shows, that the action is canceled. But if you see on the action output field, you find the logs which definitely come later the canceling time.<br>
We are using version 3.1.0 with python actions.</p>
<p>Does anyone else have this problem?</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/canceling-action-execution/1355">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/canceling-action-execution/1355</link>
          <pubDate>Fri, 17 Jul 2020 13:44:06 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1355</guid>
          <source url="https://forum.stackstorm.com/t/canceling-action-execution/1355.rss">Canceling action execution</source>
        </item>
        <item>
          <title>Python Action Error</title>
          <dc:creator><![CDATA[enflo]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>I created a new pack with a series of Actions, and the Actions written in python using the st2common library give me the following error:</p>
<pre><code class="lang-auto">Traceback (most recent call last):
  File "/5ed656266cb8de055c5e9598/service.py", line 9, in &lt;module&gt;
    from st2common.util.shell import quote_unix
ImportError: No module named st2common.util.shell
</code></pre>
<p>I was looking for how to install st2common or how to access the package, but I didn’t succeed. Can someone help me?</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/python-action-error/1262">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/python-action-error/1262</link>
          <pubDate>Tue, 02 Jun 2020 13:52:30 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1262</guid>
          <source url="https://forum.stackstorm.com/t/python-action-error/1262.rss">Python Action Error</source>
        </item>
        <item>
          <title>Zabbix monitoring</title>
          <dc:creator><![CDATA[Anushree]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>Hi,</p>
<p>when trying to enable monitoring for zabbix , I am getting follow error on my command line.<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/original/1X/7388450539687219c3147845d44e3da0ba998cad.png" data-download-href="/uploads/short-url/gu2REAfDaOJdjVePQqtePQNJsuh.png?dl=1" title="image" rel="nofollow noopener"><img src="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/original/1X/7388450539687219c3147845d44e3da0ba998cad.png" alt="image" data-base62-sha1="gu2REAfDaOJdjVePQqtePQNJsuh" width="690" height="250" data-small-upload="https://aws1.discourse-cdn.com/standard10/uploads/stackstorm/optimized/1X/7388450539687219c3147845d44e3da0ba998cad_2_10x10.png"></a></div><p></p>
<p>Please help !!</p>
<p>[root@localhost stackstorm]# st2 pack install zabbix<br>
Failed to authenticate with credentials provided in the config.<br>
ERROR: 401 Client Error: Unauthorized<br>
MESSAGE: Invalid or missing credentials for url: <a href="http://127.0.0.1:9100/tokens" rel="nofollow noopener">http://127.0.0.1:9100/tokens</a></p>
<p>[root@localhost stackstorm]# cd /root/<br>
[root@localhost ~]# st2 pack install zabbix<br>
Failed to authenticate with credentials provided in the config.<br>
ERROR: 401 Client Error: Unauthorized<br>
MESSAGE: Invalid or missing credentials for url: <a href="http://127.0.0.1:9100/tokens" rel="nofollow noopener">http://127.0.0.1:9100/tokens</a></p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/zabbix-monitoring/1221">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/zabbix-monitoring/1221</link>
          <pubDate>Fri, 08 May 2020 14:01:23 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1221</guid>
          <source url="https://forum.stackstorm.com/t/zabbix-monitoring/1221.rss">Zabbix monitoring</source>
        </item>
        <item>
          <title>UseCase Functionality</title>
          <dc:creator><![CDATA[Anushree]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>Hi All,</p>
<p>I am new to this tool, i have installed it completely via documentation , but unable to understand, how it will be integrated with various Elementary layer tool in my environment.<br>
If we can have a session on this , then it would be great.</p>
<p>Thanks &amp; Regards<br>
Anushree</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/usecase-functionality/1199">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/usecase-functionality/1199</link>
          <pubDate>Wed, 29 Apr 2020 16:48:15 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1199</guid>
          <source url="https://forum.stackstorm.com/t/usecase-functionality/1199.rss">UseCase Functionality</source>
        </item>
        <item>
          <title>Reg st2-docker persistancy</title>
          <dc:creator><![CDATA[kaarunyapooven]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>hi Team,</p>
<p>Please help to know, what are all the ways the st2-docker could be persisted in the case of docker restarted or the system reboot.<br>
I should not be losing any changes, it should work as before or with minimal changes. Please guide.<br>
other than the below any other volumes are to be created/added. As I was seeing st2chatops.env variable is reset to the initial when the system rebooted or docker is restarted.</p>
<p>volumes:<br>
mongo-volume:<br>
mongo-configdb-volume:<br>
postgres-volume:<br>
rabbitmq-volume:<br>
redis-volume:<br>
stackstorm-packs-volume:<br>
stackstorm-virtualenvs-volume:<br>
stackstorm-configs-volume:<br>
stackstorm-log-volume:</p>
            <p><small>3 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/reg-st2-docker-persistancy/1196">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/reg-st2-docker-persistancy/1196</link>
          <pubDate>Wed, 29 Apr 2020 06:14:58 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1196</guid>
          <source url="https://forum.stackstorm.com/t/reg-st2-docker-persistancy/1196.rss">Reg st2-docker persistancy</source>
        </item>
        <item>
          <title>How to clear stackstorm datastore</title>
          <dc:creator><![CDATA[barumugham]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>Hi can you pls tell me how to clear keyvalue pairs in datastore. right now I have key values pairs like<br>
this<br>
{<br>
“encrypted”: false,<br>
“name”: “ocid1.tenancy.oc1.xxxy2123423”,<br>
“scope”: “st2kv.user”,<br>
“secret”: true,<br>
“user”: “scouser”,<br>
“value”: "{“deployment_info_sync_path”: “}”<br>
},<br>
and another one like this with the same name but the user is different</p>
<p>{<br>
“encrypted”: false,<br>
“name”: “ocid1.tenancy.oc1.xxxy2123423”,<br>
“scope”: “st2kv.user”,<br>
“secret”: true,<br>
“user”: “scuser”,<br>
“value”: "{“deployment_info_sync_path”: “}”<br>
}</p>
<p>I want to delete the one with the user value <strong>scouser</strong>. If I give command like st2 key delete ( I am not aware how to frame the scouser here since the 2 users have the same name(requirement))</p>
<p>also if i give st2 key delete  ocid1.tenancy.oc1.xxxy2123423 it is not even deleting a single record.  Please tell me how to filter and delete scouser here ? As I am new to stackstorm appreciate your help.</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/how-to-clear-stackstorm-datastore/1176">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/how-to-clear-stackstorm-datastore/1176</link>
          <pubDate>Fri, 17 Apr 2020 11:21:44 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1176</guid>
          <source url="https://forum.stackstorm.com/t/how-to-clear-stackstorm-datastore/1176.rss">How to clear stackstorm datastore</source>
        </item>
        <item>
          <title>MySQL support as a StackStorm backend</title>
          <dc:creator><![CDATA[puneet]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>we need to check that is there any stable version of Stackstorm with mysql Database.</p>
            <p><small>5 posts - 3 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/mysql-support-as-a-stackstorm-backend/1154">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/mysql-support-as-a-stackstorm-backend/1154</link>
          <pubDate>Wed, 08 Apr 2020 14:24:57 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1154</guid>
          <source url="https://forum.stackstorm.com/t/mysql-support-as-a-stackstorm-backend/1154.rss">MySQL support as a StackStorm backend</source>
        </item>
        <item>
          <title>Install pack dependencies using a custom pypi mirror?</title>
          <dc:creator><![CDATA[kedare]]></dc:creator>
          <category>Packages</category>
          <description><![CDATA[
            <p>Hello.</p>
<p>I would like to know if there is a way to setup Stackstorm to use a custom pypi mirror to install pack dependencies ?<br>
We have internal ones that are not published publicly and so far I could not find a way to do this ?</p>
<p>I found this <a href="https://docs.stackstorm.com/packs.html#installing-packs-from-private-repositories" class="inline-onebox" rel="nofollow noopener">Packs — StackStorm 3.1.0 documentation</a><br>
But AFAIK this will not do anything about getting the rependencies from requirements.txt from a specific pypi mirror.<br>
Same for this: <a href="https://docs.stackstorm.com/packs.html#hosting-your-own-pack-index" class="inline-onebox" rel="nofollow noopener">Packs — StackStorm 3.1.0 documentation</a></p>
<p>Thanks.</p>
            <p><small>2 posts - 1 participant</small></p>
            <p><a href="https://forum.stackstorm.com/t/install-pack-dependencies-using-a-custom-pypi-mirror/1148">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/install-pack-dependencies-using-a-custom-pypi-mirror/1148</link>
          <pubDate>Tue, 07 Apr 2020 13:24:56 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1148</guid>
          <source url="https://forum.stackstorm.com/t/install-pack-dependencies-using-a-custom-pypi-mirror/1148.rss">Install pack dependencies using a custom pypi mirror?</source>
        </item>
        <item>
          <title>Stackstorm with Kubernetes HA - Helm 3</title>
          <dc:creator><![CDATA[satheesh]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <blockquote>
<p>helm install stackstorm/stackstorm-ha --generate-name</p>
</blockquote>
<p>manifest_sorter.go:192: info: skipping unknown hook: “crd-install”<br>
Error: unable to build kubernetes objects from release manifest: [unable to decode “”: resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 2, error found in <span class="hashtag">#10</span> byte of …|mespace":2320055036}|…, bigger context …|tackstorm-ha-1583759760-rabbitmq-ha",“namespace”:2320055036}}|…, unable to decode “”: resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 2, error found in <span class="hashtag">#10</span> byte of …|mespace":2320055036}|…, bigger context …|tackstorm-ha-1583759760-rabbitmq-ha",“namespace”:2320055036},“type”:“Opaque”}|…, unable to decode “”: resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 2, error found in <span class="hashtag">#10</span> byte of …|mespace":2320055036}|…, bigger context …|tackstorm-ha-1583759760-rabbitmq-ha",“namespace”:2320055036},“rules”:[{“apiGroups”:[""],“resources”:|…, unable to decode “”: resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 2, error found in <span class="hashtag">#10</span> byte of …|mespace":2320055036}|…, bigger context …|tackstorm-ha-1583759760-rabbitmq-ha",“namespace”:2320055036},“roleRef”:{“apiGroup”:“rbac.authorizati|…, unable to decode “”: resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 2, error found in <span class="hashtag">#10</span> byte of …|mespace”:2320055036}|…, bigger context …|ha-1583759760-rabbitmq-ha-discovery",“namespace”:2320055036},“spec”:{“clusterIP”:“None”,“ports”:[{“n|…, unable to decode “”: resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 2, error found in <span class="hashtag">#10</span> byte of …|mespace”:2320055036}|…, bigger context …|tackstorm-ha-1583759760-rabbitmq-ha",“namespace”:2320055036},“spec”:{“ports”:[{“name”:“http”,“port”:|…, unable to decode “”: resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 2, error found in <span class="hashtag">#10</span> byte of …|mespace":2320055036}|…, bigger context …|tackstorm-ha-1583759760-rabbitmq-ha",“namespace”:2320055036},“spec”:{“podManagementPolicy”:"OrderedR|…, unable to recognize “”: no matches for kind “EtcdCluster” in version “<a href="http://etcd.database.coreos.com/v1beta2" rel="nofollow noopener">etcd.database.coreos.com/v1beta2</a>”]</p>
<p>Seems this  " no matches for kind “EtcdCluster” in version “<a href="http://etcd.database.coreos.com/v1beta2" rel="nofollow noopener">etcd.database.coreos.com/v1beta2</a>” cause the error. Any lead?</p>
            <p><small>3 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/stackstorm-with-kubernetes-ha-helm-3/1103">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/stackstorm-with-kubernetes-ha-helm-3/1103</link>
          <pubDate>Mon, 09 Mar 2020 13:22:14 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1103</guid>
          <source url="https://forum.stackstorm.com/t/stackstorm-with-kubernetes-ha-helm-3/1103.rss">Stackstorm with Kubernetes HA - Helm 3</source>
        </item>
        <item>
          <title>Migrating script to actions</title>
          <dc:creator><![CDATA[jezk]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>I have a script that has multiple functions and does multiple different tasks.<br>
When migrating to a pack with st2 actions, am I correct that each task/function in the original script migrates to a single action in a single py file and yaml file within the pack?<br>
Thanks.</p>
            <p><small>5 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/migrating-script-to-actions/1053">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/migrating-script-to-actions/1053</link>
          <pubDate>Thu, 13 Feb 2020 21:18:26 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1053</guid>
          <source url="https://forum.stackstorm.com/t/migrating-script-to-actions/1053.rss">Migrating script to actions</source>
        </item>
        <item>
          <title>ELK with Stackstorm HA</title>
          <dc:creator><![CDATA[piku]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>Can anyone let me know which is better option to fetch execution history from Stackstorm HA to ELK.</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/elk-with-stackstorm-ha/1048">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/elk-with-stackstorm-ha/1048</link>
          <pubDate>Thu, 13 Feb 2020 04:27:11 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1048</guid>
          <source url="https://forum.stackstorm.com/t/elk-with-stackstorm-ha/1048.rss">ELK with Stackstorm HA</source>
        </item>
        <item>
          <title>How to install addtional st2actionrunner for python actions</title>
          <dc:creator><![CDATA[guzzijones]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>We will eventually need to install st2actionrunner on a separate vm and give it access to our standalone stackstorm instance.  We need to do this for horizontal scaling.<br>
The Kubernetes script is sort of an overkill for our current needs.  (We need to walk before we run)</p>
<p>Is it possible to:</p>
<ol>
<li>install the stackstorm rpm/deb</li>
<li>disable all services except st2actionrunner services.</li>
<li>setup config and point rabbitmq and mongodb to appropriate uri.</li>
</ol>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/how-to-install-addtional-st2actionrunner-for-python-actions/1035">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/how-to-install-addtional-st2actionrunner-for-python-actions/1035</link>
          <pubDate>Wed, 05 Feb 2020 14:48:30 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1035</guid>
          <source url="https://forum.stackstorm.com/t/how-to-install-addtional-st2actionrunner-for-python-actions/1035.rss">How to install addtional st2actionrunner for python actions</source>
        </item>
        <item>
          <title>How to change default directory from /opt/stackstorm to custom dir?</title>
          <dc:creator><![CDATA[nihrao]]></dc:creator>
          <category>Packages</category>
          <description><![CDATA[
            <p>Hello All,</p>
<p>I am trying to configure one of our application servers to use stackstorm. As /opt is protected by root privileges and I don’t want to chmod. Can I change the directory to a custom one?</p>
<p>Thanks and Regards,<br>
Nihar</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/how-to-change-default-directory-from-opt-stackstorm-to-custom-dir/1027">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/how-to-change-default-directory-from-opt-stackstorm-to-custom-dir/1027</link>
          <pubDate>Tue, 04 Feb 2020 07:11:54 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1027</guid>
          <source url="https://forum.stackstorm.com/t/how-to-change-default-directory-from-opt-stackstorm-to-custom-dir/1027.rss">How to change default directory from /opt/stackstorm to custom dir?</source>
        </item>
        <item>
          <title>K8s PV issue for stackStorm HA</title>
          <dc:creator><![CDATA[anishkumar7070]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>I have configured kubernetes with Multinode with one master and two worker node with Kubeadm .<br>
I have created 6 directories with full access in  /mnt/resource directory whose name is below<br>
mongo1 mongo2 mongo3 rabbit1 rabbit2 rabbit3</p>
<p>i have created 6 pv …3 for rabbitmq and 3 for mongoDB each and  i have created storageclass with standardclass</p>
<h2>for mongodb  pv creation</h2>
<p>apiVersion: v1<br>
kind: PersistentVolume<br>
metadata:<br>
name: mongodb1<br>
spec:<br>
capacity:<br>
storage: 10Gi<br>
accessModes:</p>
<ul>
<li>ReadWriteOnce<br>
persistentVolumeReclaimPolicy: Retain<br>
storageClassName: my-local-storage<br>
local:<br>
path: /mnt/resource/mongo1<br>
nodeAffinity:<br>
required:<br>
nodeSelectorTerms:
<ul>
<li>matchExpressions:
<ul>
<li>key: <a href="http://kubernetes.io/hostname" rel="nofollow noopener">kubernetes.io/hostname</a><br>
operator: In<br>
values:
<ul>
<li>k8snode</li>
<li>k8snode2</li>
</ul>
</li>
</ul>
</li>
</ul>
</li>
</ul>
<h2>for RabbitMQ pv creation</h2>
<p>apiVersion: v1<br>
kind: PersistentVolume<br>
metadata:<br>
name: rabbit1<br>
spec:<br>
capacity:<br>
storage: 10Gi<br>
accessModes:</p>
<ul>
<li>ReadWriteOnce<br>
persistentVolumeReclaimPolicy: Retain<br>
storageClassName: my-local-storage<br>
local:<br>
path: /mnt/resource/rabbit1<br>
nodeAffinity:<br>
required:<br>
nodeSelectorTerms:
<ul>
<li>matchExpressions:
<ul>
<li>key: <a href="http://kubernetes.io/hostname" rel="nofollow noopener">kubernetes.io/hostname</a><br>
operator: In<br>
values:
<ul>
<li>k8snode</li>
<li>k8snode2</li>
</ul>
</li>
</ul>
</li>
</ul>
</li>
</ul>
<h2>PV is not bound for RAbbitMQ and MongoDB .Please help me how we can proceed as all pods are going in crashloop<br>
one of crashed pods of stackStorm</h2>
<p>[root@k8smaster1 /]# kubectl logs stackstorm-ha-1580637351-st2actionrunner-577648bcd-4kxzv<br>
2020-02-02 10:36:30,219 DEBUG [-] Using Python: 2.7.12 (/opt/stackstorm/st2/bin/python)<br>
2020-02-02 10:36:30,219 DEBUG [-] Using config files: /etc/st2/st2.conf,/etc/st2/st2.docker.conf,/etc/st2/st2.user.conf<br>
2020-02-02 10:36:30,219 DEBUG [-] Using logging config: /etc/st2/logging.actionrunner.conf<br>
2020-02-02 10:36:30,224 INFO [-] Connecting to database “st2” @ “stackstorm-ha-1580637351-mongodb-ha-0.stackstorm-ha-1580637351-mongodb-ha:27017,stackstorm-ha-1580637351-mongodb-ha-1.stackstorm-ha-1580637351-mongodb-ha:27017,stackstorm-ha-1580637351-mongodb-ha-2.stackstorm-ha-1580637351-mongodb-ha:27017 (replica set)” as user “admin”.<br>
2020-02-02 10:36:33,230 ERROR [-] Failed to connect to database “st2” @ “stackstorm-ha-1580637351-mongodb-ha-0.stackstorm-ha-1580637351-mongodb-ha:27017,stackstorm-ha-1580637351-mongodb-ha-1.stackstorm-ha-1580637351-mongodb-ha:27017,stackstorm-ha-1580637351-mongodb-ha-2.stackstorm-ha-1580637351-mongodb-ha:27017 (replica set)” as user “admin”: No replica set members found yet<br>
2020-02-02 10:36:33,231 ERROR [-] (PID=1) Worker quit due to exception.<br>
Traceback (most recent call last):<br>
File “/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/actionrunner.py”, line 94, in main<br>
_setup()<br>
File “/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/actionrunner.py”, line 55, in _setup<br>
register_signal_handlers=True, service_registry=True, capabilities=capabilities)<br>
File “/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py”, line 160, in setup<br>
db_setup()<br>
File “/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/database_setup.py”, line 56, in db_setup<br>
connection = db_init.db_setup_with_retry(**db_cfg)<br>
File “/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/persistence/db_init.py”, line 75, in db_setup_with_retry<br>
ssl_match_hostname=ssl_match_hostname)<br>
File “/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/persistence/db_init.py”, line 58, in db_func_with_retry<br>
return retrying_obj.call(db_func, *args, **kwargs)<br>
File “/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py”, line 206, in call<br>
return attempt.get(self._wrap_exception)<br>
File “/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py”, line 247, in get<br>
six.reraise(self.value[0], self.value[1], self.value[2])<br>
File “/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py”, line 200, in call<br>
attempt = Attempt(fn(*args, **kwargs), attempt_number, False)<br>
File “/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/db/<strong>init</strong>.py”, line 169, in db_setup<br>
ssl_match_hostname=ssl_match_hostname)<br>
File “/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/db/<strong>init</strong>.py”, line 151, in _db_connect<br>
raise e</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/k8s-pv-issue-for-stackstorm-ha/1025">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/k8s-pv-issue-for-stackstorm-ha/1025</link>
          <pubDate>Sun, 02 Feb 2020 10:55:38 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-1025</guid>
          <source url="https://forum.stackstorm.com/t/k8s-pv-issue-for-stackstorm-ha/1025.rss">K8s PV issue for stackStorm HA</source>
        </item>
        <item>
          <title>System users in StackStorm deployment: st2, stanley and root</title>
          <dc:creator><![CDATA[chris]]></dc:creator>
          <category>Operations</category>
          <description><![CDATA[
            <p>We are using the docker setup of stackstorm, but we’re a bit confused by the users used to run different components in stackstorm. We identified 3 users: root, stanley and st2.</p>
<p>A quick scan of the users used by the init scripts gave us this list:</p>
<pre><code class="lang-auto">/etc/init/st2actionrunner-worker.conf:setuid root
/etc/init/st2api.conf:setuid st2
/etc/init/st2auth.conf:setuid st2
/etc/init/st2chatops.conf:setuid st2
/etc/init/st2garbagecollector.conf:setuid st2
/etc/init/st2notifier.conf:setuid st2
/etc/init/st2resultstracker.conf:setuid st2
/etc/init/st2rulesengine.conf:setuid st2
/etc/init/st2scheduler.conf:setuid st2
/etc/init/st2sensorcontainer.conf:setuid st2
/etc/init/st2stream.conf:setuid st2
/etc/init/st2timersengine.conf:setuid st2
/etc/init/st2workflowengine.conf:setuid st2
</code></pre>
<p>You can clearly see that all services are ran by <strong>st2</strong>, except for <code>st2actionrunner-worker</code>, which is ran by <strong>root</strong> and nothing by <strong>stanley</strong>. During development of our own packs, we were sometimes confused by this setup. There seem to be some inconsistency between different packs. We observed that most packs are run as root, while checking <code>$(id)</code> with <code>core.echo</code> produces <code>1000</code> (aka stanley).</p>
<p>These inconsistencies confuse us and hinder our development.</p>
<ul>
<li>Can someone from the developer team explain the rational behind these accounts?</li>
<li>In which situations can we expect our code to run as either root, stanley or st2?</li>
<li>Is it strictly necessary to run all workers as root? Except for local administrative commands, we do not see the need to run packs as root by default.</li>
</ul>
            <p><small>3 posts - 2 participants</small></p>
            <p><a href="https://forum.stackstorm.com/t/system-users-in-stackstorm-deployment-st2-stanley-and-root/987">Read full topic</a></p>
          ]]></description>
          <link>https://forum.stackstorm.com/t/system-users-in-stackstorm-deployment-st2-stanley-and-root/987</link>
          <pubDate>Thu, 09 Jan 2020 14:46:57 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">forum.stackstorm.com-topic-987</guid>
          <source url="https://forum.stackstorm.com/t/system-users-in-stackstorm-deployment-st2-stanley-and-root/987.rss">System users in StackStorm deployment: st2, stanley and root</source>
        </item>
  </channel>
</rss>
